version: '3.8'

services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://server:3001
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    command: bun run dev
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/dandy
      - REDIS_URL=redis://redis:6379
      - CLIENT_URL=http://client:3000
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    command: bun run dev
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:
